### ISSUE TITLE
Intent already created

### ISSUE THREAD

**Issue by LindaLawton** [firebase/assistant-codelab#6]
> Create a new "Intent" called "Guess is Correct"

This intent was already imported in Assistant.zip trying to add it again results in an error that it already exists.

**Comment by embiem** [comment]
@LindaLawton are you sure that you've imported the Assistant.zip located in the /project folder and NOT in the /solution folder?

**Comment by LindaLawton** [comment]
Lol not at all sounds like that may be what I did. I didn't realize there was two files.
